// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  socketHost: "https://livetree.herokuapp.com",  // TODO: replace with heroku endpoint
  version: env.npm_package_version,
  serverUrl: 'https://livetree.herokuapp.com/', // TODO: replace with heroku endpoint
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
